version: '3'

services:
    web:
        build: .
        container_name: 'web'
        # entrypoint: docker_files/entrypoint.sh
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app/
        ports: 
            - 8000:8000