# Generated by Django 4.2.1 on 2023-05-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_bold_copy', models.TextField(blank=True, null=True, verbose_name='About Bold Copy')),
                ('about_reg_copy', models.TextField(blank=True, null=True, verbose_name='About Regular Copy')),
            ],
            options={
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_copy', models.TextField(blank=True, null=True, verbose_name='Contact Copy')),
            ],
            options={
                'verbose_name_plural': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(max_length=6, verbose_name='Logo Initials')),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Home Section',
            },
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Skill Type',
            },
        ),
        migrations.CreateModel(
            name='SkillSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_resume_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Resume URL')),
                ('skill_github_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='GitHub URL')),
                ('skill_card_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills1', to='portfolio.skilltype')),
                ('skill_card_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills2', to='portfolio.skilltype')),
                ('skill_card_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills3', to='portfolio.skilltype')),
            ],
            options={
                'verbose_name_plural': 'Skill Section',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=64)),
                ('skill_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skilltype')),
            ],
        ),
    ]
